name: Test iOS e2e
on:
  pull_request:
    paths:
        - 'Example/**'
  push:
    branches:
      - master
  workflow_dispatch:
# env:
  #  DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
jobs:
  build:
    runs-on: macos-latest
    env:
      WORKING_DIRECTORY: Example
    concurrency:
      group: ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Get Xcode version
        run: xcodebuild -version
      - name: Install AppleSimulatorUtils
        run: brew tap wix/brew && brew install applesimutils
      - name: Install root node dependencies
        run: yarn
      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: List devices
        run: ls /Users/runner/Library/Developer/CoreSimulator/Devices
      - name: Install pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod install
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build-e2e-ios
      - name: Test app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn test-e2e-ios
